name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            bin: bfg-linux-x64
          - os: ubuntu-24.04-arm
            rid: linux-arm64
            bin: bfg-linux-arm64
          - os: windows-latest
            rid: win-x64
            bin: bfg-win-x64.exe
          - os: windows-latest
            rid: win-arm64
            bin: bfg-win-arm64.exe
          - os: macos-latest
            rid: osx-arm64
            bin: bfg-osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

      - name: make binary
        run: dotnet publish -r ${{ matrix.rid }} -c Release -p:PublishAot=true -o ./publish

      - name: rename binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv ./publish/*.exe ./publish/${{ matrix.bin }}
          else
            # Finds the binary (ignoring .pdb or .dbg files) and renames it
            mv $(find ./publish -maxdepth 1 -type f ! -name "*.*") ./publish/${{ matrix.bin }}
          fi

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin }}
          path: ./publish/${{ matrix.bin }}
